services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db-finance
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "finance"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-finance
    environment:
       PMA_HOST: mysql-db-finance
       PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - mysql

volumes:
  mysql_data: